### ISSUE TITLE
Github Dark Theme

### ISSUE THREAD

**Issue by qwelias** [vovanmix/github-dark-theme#10]
There's another extension https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp/related
which was published a little earlier and your's look way too similar.

Have you based your work on top of this extension, if so why didn't you credit it?
What's the difference aside from font?

**Comment by vovanmix** [comment]
No I didn't know about that extension and did mine from scratch

**Comment by queengooborg** [comment]
Actually, @qwelias, if you search for the developer, you'll find that their extension is a fork of this one (https://github.com/poychang/github-dark-theme).  If anything, it's the other extension that should be giving credit to this one.  :)
