### ISSUE TITLE
Feature Request: Github Enterprise

### ISSUE THREAD

**Issue by jjscaria** [vovanmix/github-dark-theme#6]
Can you add support for Enterprise Github/Gist?

github.domain.com

**Comment by vovanmix** [comment]
Thanks for reporting this! It should work in `0.10`. I just published it, it may take several hours to get public. Please let me know if it doesn't.

**Comment by jjscaria** [comment]
The extension never updated. I tried uninstalling and reinstalling but, I am getting this error:
```
There was a problem with the download. Please contact the developer or try again later.
```
I tried manually updating, didnt work.

Also, I see that you only added Github and not Gist. Was that intentional?

**Comment by vovanmix** [comment]
oh, unfortunately it looks like it's not possible to match a url that look like `github.*.com`. And I can't add a matcher for every possible domain because it will mess up with other sites then.
https://developer.chrome.com/extensions/match_patterns
I reverted it back, sorry!
